// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kypaiixrszpljxktawne.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5cGFpaXhyc3pwbGp4a3Rhd25lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2Nzc4ODgsImV4cCI6MjA3NDI1Mzg4OH0.z70x8s0KSjxhZ8A36oiMlbQ0FpczSPptHLz1Jr7dZZw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});